language: python
sudo: required
python:
  - "2.7"
services:
  - docker
addons:
  firefox: 'latest'
env:
  global:
    - COMPOSE_PROJECT_NAME=addonsserver
    - DOCKER_NAME=addonsserver_web_1
before_script:
  - docker-compose pull
  - docker-compose up -d
  - make initialize_docker
script:
  - mv conftest.py _conftest.py
  - py.test --base-url http://$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $DOCKER_NAME) --driver Firefox --html results.html --junitxml junit.xml src/olympia/amo/tests/ui
notifications:
  email: false
