language: python
sudo: required
python:
  - "2.7"
services:
  - docker
addons:
  firefox: 'latest'
env:
  global:
    - COMPOSE_PROJECT_NAME=addonsserver
    - DOCKER_NAME=addonsserver_web_1
before_script:
  - docker-compose pull
  - docker-compose up -d
  - docker exec -t -i ${DOCKER_NAME} python manage.py reset_db --noinput
  - docker exec -t -i ${DOCKER_NAME} python manage.py syncdb --noinput
  - docker exec -t -i ${DOCKER_NAME} python manage.py loaddata initial.json
  - docker exec -t -i ${DOCKER_NAME} python manage.py import_prod_versions
  - docker exec -t -i ${DOCKER_NAME} schematic --fake src/olympia/migrations/
  - docker exec -t -i ${DOCKER_NAME} python manage.py loaddata zadmin/users
  - docker exec -t -i ${DOCKER_NAME} update_assets
  - docker exec -t -i ${DOCKER_NAME} populate_data
script:
  - mv conftest.py _conftest.py
  - py.test --base-url http://$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $DOCKER_NAME) --driver Firefox --html results.html --junitxml junit.xml src/olympia/amo/tests/ui
notifications:
  email: false
