language: python
sudo: false
python:
  - "2.7"
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=assets
  - TOX_ENV=es
  - TOX_ENV=addons
  - TOX_ENV=amo
  - TOX_ENV=devhub
  - TOX_ENV=editors
  - TOX_ENV=main
services:
  - memcached
addons:
  apt_packages:
    - swig
  firefox: 'latest'
before_install:
  - scripts/travis_es.sh
  - /tmp/elasticsearch/elasticsearch-1.6.2/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false
install:
  - nvm current
  - nvm deactivate
  - nvm install 4
  - nvm use 4
  - pip install tox==1.8.1
before_script:
  - mysql -e 'create database olympia;'
  - node --version
script:
  - RUNNING_IN_CI=True tox -v -e $TOX_ENV --recreate
notifications:
  email: false
